app:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

root:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: nelmio_api_doc_index
    permanent: true